### PR TITLE
upgraded to Umbraco 10

### PR DESCRIPTION
**Pull request by skartknet**
Upgraded support for Umbraco V10, modifying the namespaces and upgrading to .NET 6

### CODE REVIEW

**Comment by abjerner** [comment]
Hi @skartknet 

Thanks for this PR 👍 

May I ask why you need this for Umbraco 10? We haven't used the grid in anything Umbraco 9+, so I wasn't planning on supporting this package beyond Umbraco 8.

Anyways, the following files seems to be leftovers from the upgrade tool. I don't really have a need for them in the repo - could you remove them?

- src/Skybrud.Umbraco.GridData.Dtge/.upgrade-assistant
- src/Skybrud.Umbraco.GridData.Dtge/AnalysisReport.sarif
- src/Skybrud.Umbraco.GridData.Dtge/UpgradeReport.sarif
- src/Skybrud.Umbraco.GridData.Dtge/UpgradeReport.sarif

The dependency for `Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers` should also be redundant now that the you have upgraded the project. Could you remove this as well?

I'll try finding some time to look at the rest of your PR 😉

**Comment by skartknet** [comment]
Hey @abjerner , I have removed the files and dependency, sorry that was a bit lazy on my part  :sweat_smile:

The reason for using this is because we are upgrading an Umbraco 7 site that uses Grid+DTGE to Umbraco 10.

Can I ask you why do you think the plugin is not needed anymore? The editing experience in Umbraco hasn't changed significantly since the release of Nested Content. I personally don't like to use the Grid, but I can see that people that were using it still might have the same reason to continue doing the same with Umbraco 10. In fact, DTGE still supports v10.

**Comment by abjerner** [comment]
Thanks for the changes @skartknet 👍 

This package is very much a niche package, which was why I wasn't planning on supporting it going forward. I've had no requests to support it for Umbraco 9, so the latest version is still for Umbraco 8.

As a comparison, Skybrud.Umbraco.GridData.Dtge has had 17 downloads on NuGet since the 1st of December, while for instance Skybrud.Umbraco.GridData has had 6.740 downloads and Skybrud.Umbraco.Redirects has had 15.240 downloads in the same period.

Packages also take time to maintain and support. I can't remember whether we ever ended up using this package on a client project, but even with Umbraco 8, we started using the block list instead, and haven't made a grid site since then. So as a company, we don't really have a need for this package.

That leaves it up to me to maintain the package in my spare time. Technically I'm allowed do it on company time, but I rarely have the time to - or if I do, there's usually more important packages to maintain (we have 100+ packages on NuGet).

But with that being said, PRs like this one is much appreciated, so I'll look into getting this tested, merged and then released on NuGet 😉

**Comment by skartknet** [comment]
It makes sense that with 17 downloads there's no need to spend time on it.

I'm using the package to extract clean content for indexing, but I guess I can just index the whole json instead.

Thanks for the explanation.

**Comment by abjerner** [comment]
Yeah, it's not a lot. But since you made this PR, I'm looking into pushing a release anyways 😉

**Comment by abjerner** [comment]
Again thanks a lot 👍 

I've now pushed a new [**`v4.0.0`**](https://github.com/skybrud/Skybrud.Umbraco.GridData.Dtge/releases/tag/v4.0.0) release for Umbraco 10, which include this PR 😉

**Pull request merged**
